namespace Compositor.Desktop;

/// <summary>
/// Which pointer tool is in hand. The rail draws one button per tool and the Tools menu has a row for each, so
/// the two stay in step by both being built from this list.
/// </summary>
internal enum Tool
{
    Pan,
    Move,
    Marquee,
    Ellipse,
    Lasso,
    Polygon,
    Wand,
    Object,
    Brush,
    Clone,
    Blur,
    Liquify,
    Smudge,
    Heal,
    Eyedropper,
    Type,
    Crop,
    Shape,
    Gradient,
    HistoryBrush,
    Path,
    PathSelection,
    ShapeEllipse,
    Triangle,
    PolygonShape,
    Star,
    Line,
    CustomShape,
    RotateView,
    Zoom,
    PatternStamp,
    ArtHistory,
    Eraser,
    BackgroundEraser,
    MagicEraser,
    Bucket,
    Sharpen,
    AdjustmentBrush,
    Dodge,
    Burn,
    Sponge,
    Pen,
    FreeformPen,
    CurvaturePen,
    AddAnchor,
    DeleteAnchor,
    ConvertAnchor,
    VerticalType,
    VerticalTypeMask,
    SelectionBrush,
    MagneticLasso,
    QuickSelection,
    PerspectiveCrop,
    Slice,
    SliceSelect,
    Frame,
    ColorSampler,
    Ruler,
    Note,
    Count,
    Remove,
    HealingBrush,
    Patch,
    ContentMove,
    RedEye,
    Pencil,
    ColorReplacement,
    MixerBrush,

    TypeMask,

}

/// <summary>Which of the brush's amounts was asked for, by the Tools menu or the options bar.</summary>
internal enum BrushSetting
{
    Size,
    Hardness,
    Opacity,
    Colour,
    /// <summary>How far the Blur brush softens, which is its own setting rather than the brush's size.</summary>
    Radius,
}
